name: netflix_app
description: A new Flutter project.
#
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  flutter_native_splash: ^2.3.1
  firebase_core: ^2.15.0
  firebase_auth: ^4.7.2
  flutter_bloc: ^8.1.3
  bloc: ^8.1.2
  modal_progress_hud_nsn: ^0.4.0
  email_auth: ^1.0.0
  email_otp: ^2.0.1
  pin_code_fields: ^8.0.1
  http: 
  equatable: ^2.0.5
  dio: ^5.3.2
  conditional_builder_null_safety: ^0.0.6
  video_player: ^2.7.1
  webview_flutter: ^4.2.3
  flutter_inappwebview: ^5.7.2+3
  chewie: ^1.0.2
  
  
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  
  uses-material-design: true

  
  assets:
    - assets/images/
    

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

 
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
       
  
    - family: Inter
      fonts:
        - asset: fonts/Inter-Regular.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
 
