// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClf6EUK-Pc08fQoJBGAB9x5J55lU6GeW8',
    appId: '1:124839745687:web:6f616ac5093c41f87831d2',
    messagingSenderId: '124839745687',
    projectId: 'netfilex-app-c5f5c',
    authDomain: 'netfilex-app-c5f5c.firebaseapp.com',
    storageBucket: 'netfilex-app-c5f5c.appspot.com',
    measurementId: 'G-BNC4W2J3P6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuMWMaMhTu_BTDH2GFodFd2sBdJLldLaQ',
    appId: '1:124839745687:android:009dc9607192da977831d2',
    messagingSenderId: '124839745687',
    projectId: 'netfilex-app-c5f5c',
    storageBucket: 'netfilex-app-c5f5c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfEfCTuYNZTmR1C7BWVKhL-RHhBcHZFJI',
    appId: '1:124839745687:ios:aecf778cbd05f41f7831d2',
    messagingSenderId: '124839745687',
    projectId: 'netfilex-app-c5f5c',
    storageBucket: 'netfilex-app-c5f5c.appspot.com',
    iosClientId: '124839745687-kr21flhkc5inpvf9js2da3vas49lb9de.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfEfCTuYNZTmR1C7BWVKhL-RHhBcHZFJI',
    appId: '1:124839745687:ios:be2101e59365f0f17831d2',
    messagingSenderId: '124839745687',
    projectId: 'netfilex-app-c5f5c',
    storageBucket: 'netfilex-app-c5f5c.appspot.com',
    iosClientId: '124839745687-sg4jm3ctulno4omff7lgta01mv2br06b.apps.googleusercontent.com',
    iosBundleId: 'com.example.netflixApp.RunnerTests',
  );
}
